Pin Markupsafe version
Flask is requiring markupsafe, but current version has deprecated some methods
that are required by our flask version

`ImportError: cannot import name 'soft_unicode' from 'markupsafe'`